# Site settings
title: twilco
email: twilco.o@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://twilco.github.io" # the base hostname & protocol for your site
github_username: twilco
future: true # enable display of posts with their dates set in the future

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll/footnotes

# Build settings
markdown: kramdown
