# Site settings
title: twilco
email: tyler.l.wilcock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://twilco.github.io" # the base hostname & protocol for your site
twitter_username: tylerwilcock 
github_username: twilco

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
